version: '3'

services:
  reverse-proxy:
    image: traefik:1.7.13
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  isotope-server:
    image: avalverdelefebvre/react-imapsmtp-docker:server-latest
    ports:
      - "9010:9010"
    labels:
      - traefik.backend=lefebvre-imap-smtp-server
      - "traefik.frontend.rule=PathPrefixStrip:/api/"

  isotope-client:
    image: avalverdelefebvre/react-imapsmtp-docker:client-newdesign-latest
    ports:
      - "8081:80"
    labels:
      - traefik.backend=lefebvre-imap-smtp-client
      - "traefik.frontend.rule=PathPrefixStrip:/"  
      
  account-api:
    image: elefebvreoncontainers/account.api:latest
    ports:
      - "8082:80"
      
  google-client:
    image: elefebvreoncontainers/google.client:latest
    ports:
      - "8088:80"

#traefik console: 8080 OK
#smtp-imap.client: 8081 
#account.service: 8082 OK
#account.gateway: 8083
#lexon.mysql.service: 8084
#lexon.service: 8085
#lexon.gateway: 8086
#portal.client: 8087
#google.client: 8088
#outlook.client: 8089
#lexon.client: 8090
#rabbitmq console: 15672 
#rabbitmq tcp: 5672
  
