version: '3'

services:
  reverse-proxy:
    image: traefik:1.7.13
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  isotope-server:
    image: avalverdelefebvre/react-imapsmtp-docker:server-latest
    ports:
      - "9010:9010"
    labels:
      - traefik.backend=lefebvre-imap-smtp-server
      - "traefik.frontend.rule=PathPrefixStrip:/api/"

  isotope-client:
    image: avalverdelefebvre/react-imapsmtp-docker:client-newdesign-latest
    ports:
      - "8081:80"
    labels:
      - traefik.backend=lefebvre-imap-smtp-client
      - "traefik.frontend.rule=PathPrefixStrip:/"  
      
  account-api:
    image: elefebvreoncontainers/account.api:latest
    ports:
      - "8082:80"
   
#account.api: 82
#account.gw: 83
#lexon.mysql.api: 84
#lexon.api: 85
#lexon.gw: 86
#portal: 87
#google: 88
#outlook: 89
#lexon-app: 90
  
